Raise required compiler to rust 1.58
For inline formatting variables.

    error: there is no argument named `key`
      --> build.rs:41:46
       |
    41 |             eprintln!("Environment variable ${key} is not set during execution of build script");
       |                                              ^^^^^

    error: there is no argument named `key`
      --> build.rs:45:46
       |
    45 |             eprintln!("Environment variable ${key} is non-UTF8 during execution of build script");
       |                                              ^^^^^